version: "3.8"

services:
  database:
    image: postgres
    container_name: goomer-lista-rango-database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - ./src/core/database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

